## Import the relevant libraries

In [1]:
import numpy as np
import pandas as pd

## Load the preprocessed data

In [2]:
data_preprocessed = pd.read_csv('Absenteeism_preprocessed.csv')
data_preprocessed.head()

Reason for Absence - Group 1  Reason for Absence - Group 2  \
0                             0                             0   
1                             0                             0   
2                             0                             0   
3                             1                             0   
4                             0                             0   

   Reason for Absence - Group 3  Reason for Absence - Group 4  Month  \
0                             0                             1      7   
1                             0                             0      7   
2                             0                             1      7   
3                             0                             0      7   
4                             0                             1      7   

   Day of the Week  Transportation Expense  Distance to Work  Age  \
0                1                     289                36   33   
1                1                     118                13   50   
2                2                     179                51   38   
3                3                     279                 5   39   
4                3                     289                36   33   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          0         2     1   
1                  239.554               31          0         1     0   
2                  239.554               31          0         0     0   
3                  239.554               24          0         2     0   
4                  239.554               30          0         2     1   

   Absenteeism Time in Hours  
0                          4  
1                          0  
2                          2  
3                          4  
4                          2

## Create the targets

In [3]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [4]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > 
                   data_preprocessed['Absenteeism Time in Hours'].median(), 1, 0)

In [5]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [6]:
data_preprocessed['Excessive Absenteeism'] = targets

In [7]:
data_preprocessed.head(7)

Reason for Absence - Group 1  Reason for Absence - Group 2  \
0                             0                             0   
1                             0                             0   
2                             0                             0   
3                             1                             0   
4                             0                             0   
5                             0                             0   
6                             0                             0   

   Reason for Absence - Group 3  Reason for Absence - Group 4  Month  \
0                             0                             1      7   
1                             0                             0      7   
2                             0                             1      7   
3                             0                             0      7   
4                             0                             1      7   
5                             0                             1      7   
6                             0                             1      7   

   Day of the Week  Transportation Expense  Distance to Work  Age  \
0                1                     289                36   33   
1                1                     118                13   50   
2                2                     179                51   38   
3                3                     279                 5   39   
4                3                     289                36   33   
5                4                     179                51   38   
6                4                     361                52   28   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          0         2     1   
1                  239.554               31          0         1     0   
2                  239.554               31          0         0     0   
3                  239.554               24          0         2     0   
4                  239.554               30          0         2     1   
5                  239.554               31          0         0     0   
6                  239.554               27          0         1     4   

   Absenteeism Time in Hours  Excessive Absenteeism  
0                          4                      1  
1                          0                      0  
2                          2                      0  
3                          4                      1  
4                          2                      0  
5                          2                      0  
6                          8                      1

## A comment on the targets

In [8]:
# Checking the balance between targets in the data set (usually for some is 60/40, mostly balanced is 55/45)
targets.sum() / targets.shape[0]

0.45571428571428574

In [9]:
# Create a checkpoint 
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours'], axis=1)

In [10]:
# Check whether the checkpoint dataset is the same as before
data_with_targets is data_preprocessed

False

In [11]:
data_with_targets.head()

Reason for Absence - Group 1  Reason for Absence - Group 2  \
0                             0                             0   
1                             0                             0   
2                             0                             0   
3                             1                             0   
4                             0                             0   

   Reason for Absence - Group 3  Reason for Absence - Group 4  Month  \
0                             0                             1      7   
1                             0                             0      7   
2                             0                             1      7   
3                             0                             0      7   
4                             0                             1      7   

   Day of the Week  Transportation Expense  Distance to Work  Age  \
0                1                     289                36   33   
1                1                     118                13   50   
2                2                     179                51   38   
3                3                     279                 5   39   
4                3                     289                36   33   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          0         2     1   
1                  239.554               31          0         1     0   
2                  239.554               31          0         0     0   
3                  239.554               24          0         2     0   
4                  239.554               30          0         2     1   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

## Select the inputs for the regression

In [12]:
data_with_targets.shape

(700, 15)

In [13]:
data_with_targets.iloc[:, :14]

Reason for Absence - Group 1  Reason for Absence - Group 2  \
0                               0                             0   
1                               0                             0   
2                               0                             0   
3                               1                             0   
4                               0                             0   
..                            ...                           ...   
695                             1                             0   
696                             1                             0   
697                             1                             0   
698                             0                             0   
699                             0                             0   

     Reason for Absence - Group 3  Reason for Absence - Group 4  Month  \
0                               0                             1      7   
1                               0                             0      7   
2                               0                             1      7   
3                               0                             0      7   
4                               0                             1      7   
..                            ...                           ...    ...   
695                             0                             0      5   
696                             0                             0      5   
697                             0                             0      5   
698                             0                             1      5   
699                             0                             1      5   

     Day of the Week  Transportation Expense  Distance to Work  Age  \
0                  1                     289                36   33   
1                  1                     118                13   50   
2                  2                     179                51   38   
3                  3                     279                 5   39   
4                  3                     289                36   33   
..               ...                     ...               ...  ...   
695                2                     179                22   40   
696                2                     225                26   28   
697                3                     330                16   28   
698                3                     235                16   32   
699                3                     291                31   40   

     Daily Work Load Average  Body Mass Index  Education  Children  Pets  
0                    239.554               30          0         2     1  
1                    239.554               31          0         1     0  
2                    239.554               31          0         0     0  
3                    239.554               24          0         2     0  
4                    239.554               30          0         2     1  
..                       ...              ...        ...       ...   ...  
695                  237.656               22          1         2     0  
696                  237.656               24          0         1     2  
697                  237.656               25          1         0     0  
698                  237.656               25          1         0     0  
699                  237.656               25          0         1     1  

[700 rows x 14 columns]

In [14]:
unscaled_inputs = data_with_targets.iloc[:, :-1]

## Standardization on the Dataset

In [15]:
from sklearn.preprocessing import StandardScaler

absenteeism_scaler = StandardScaler() 

In [16]:
# fit the dataset to StandardScaler object
absenteeism_scaler.fit(unscaled_inputs)

StandardScaler()

In [17]:
# transform the unscaled data
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [18]:
scaled_inputs

array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         0.88046927,  0.26848661],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.91902997, -0.58968976],
       ...,
       [ 1.73205081, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035,  0.26848661]])

In [19]:
scaled_inputs.shape

(700, 14)

## Split the data into train & test and shuffle

### Import the relevant module

In [20]:
from sklearn.model_selection import train_test_split

### Split

In [21]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size=0.8, random_state=20)

In [22]:
print(x_train.shape, x_test.shape)

(560, 14) (140, 14)


In [23]:
print(y_train.shape, y_test.shape)

(560,) (140,)


## Apply Machine Learning Algorithms

### Import the relevant libraries

In [24]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [25]:
reg = LogisticRegression()

In [26]:
reg.fit(x_train, y_train)

LogisticRegression()

In [27]:
# print the train accuracy
reg.score(x_train, y_train)

0.7839285714285714

### Manually check the accuracy

In [28]:
model_outputs = reg.predict(x_train)
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [29]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [30]:
model_outputs == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [31]:
np.sum(model_outputs == y_train)

439

In [33]:
model_outputs.shape[0]

560

In [34]:
# Print train accuracy 
print(np.sum(model_outputs == y_train) / model_outputs.shape[0])

0.7839285714285714


## Create a summary table

### Finding the inctercept and coefficient

In [35]:
reg.intercept_

array([-0.22206736])

In [36]:
reg.coef_

array([[ 2.07601767,  0.33504757,  1.56162303,  1.32927434,  0.18793677,
        -0.07062253,  0.70639316, -0.03986811, -0.20089491, -0.00456366,
         0.31933564, -0.135508  ,  0.38172443, -0.3332426 ]])

In [38]:
unscaled_inputs.columns.values

array(['Reason for Absence - Group 1', 'Reason for Absence - Group 2',
       'Reason for Absence - Group 3', 'Reason for Absence - Group 4',
       'Month', 'Day of the Week', 'Transportation Expense',
       'Distance to Work', 'Age', 'Daily Work Load Average',
       'Body Mass Index', 'Education', 'Children', 'Pets'], dtype=object)

In [39]:
feature_name = unscaled_inputs.columns.values

### Create summary table

In [40]:
summary_table = pd.DataFrame(columns=['Feature name'], data=feature_name)
summary_table['Coefficient'] = np.transpose(reg.coef_)
summary_table

Feature name  Coefficient
0   Reason for Absence - Group 1     2.076018
1   Reason for Absence - Group 2     0.335048
2   Reason for Absence - Group 3     1.561623
3   Reason for Absence - Group 4     1.329274
4                          Month     0.187937
5                Day of the Week    -0.070623
6         Transportation Expense     0.706393
7               Distance to Work    -0.039868
8                            Age    -0.200895
9        Daily Work Load Average    -0.004564
10               Body Mass Index     0.319336
11                     Education    -0.135508
12                      Children     0.381724
13                          Pets    -0.333243

In [42]:
# Add the intercept to summary table
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table =  summary_table.sort_index()
summary_table

Feature name  Coefficient
0                      Intercept    -0.222067
1                      Intercept    -0.222067
2   Reason for Absence - Group 1     2.076018
3   Reason for Absence - Group 2     0.335048
4   Reason for Absence - Group 3     1.561623
5   Reason for Absence - Group 4     1.329274
6                          Month     0.187937
7                Day of the Week    -0.070623
8         Transportation Expense     0.706393
9               Distance to Work    -0.039868
10                           Age    -0.200895
11       Daily Work Load Average    -0.004564
12               Body Mass Index     0.319336
13                     Education    -0.135508
14                      Children     0.381724
15                          Pets    -0.333243