## Numpy Tutorial

In [1]:
import numpy as np

In [2]:
# Create a numpy array:
a = np.array([i for i in range(6)])
a

array([0, 1, 2, 3, 4, 5])

In [4]:
# Access to numpy array element (the same as Python list)
a[0], a[1]

(0, 1)

In [7]:
# New functions to get list contain indices U want to select (only in numpy)
b = a[[0, 2, -1]]
b

array([0, 2, 5])

### Get array type:

In [8]:
# Get array type: dtype 
a.dtype

dtype('int32')

### Dimensions and Shapes

In [16]:
# Create a 2D array
A = np.array([
#   0.  1. 2.
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [11]:
# print shape
A.shape

(3, 3)

In [12]:
# number of dimension
A.ndim

2

In [14]:
# Size of numpy array (the number of total elements):
A.size

9

### Note: If the shape is not consistent, it will fall back to Python object type

### Indexing and Slicing Matrices

In [19]:
A[1] # get a row

array([4, 5, 6])

In [20]:
A[1, 0] # get an element 

4

In [21]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
# Using numpy helps a lot in indicing

### Summary Statistics

In [26]:
# sum, mean, standard deviation (even for matrices)
A.sum()

45

In [27]:
A.mean()

5.0

In [28]:
A.std()

2.581988897471611

### Broadcasting and Vectorised operations

In [29]:
# create an array in range given
arr = np.arange(4)

In [30]:
arr

array([0, 1, 2, 3])

In [32]:
# With numpy array, you can add, multiply, ... a number with every element in that array
arr + 10

array([10, 11, 12, 13])

In [33]:
arr * 10

array([ 0, 10, 20, 30])

In [34]:
arr - 10

array([-10,  -9,  -8,  -7])

In [36]:
arr / 10

array([0. , 0.1, 0.2, 0.3])

In [37]:
# You can also broadcasting (change size of two array to suit in operations), which has already been done before by ya :>

### Linear Algebra (Dai so tuyen tinh)

In [3]:
A = np.array(
    [[1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])

In [5]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [7]:
# Multiply two matrices
A.dot(B) 

array([[20, 14],
       [56, 41],
       [92, 68]])

In [8]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [9]:
# row -> col & col -> row
B.T

array([[6, 4, 2],
       [5, 3, 1]])

### Useful Numpy Functions:

`reshape`: shape the list to the shape designated

`linspace`: create a numpy array with equal increase (e.g [1, 3, 5])

`zeros`, `ones`, `empty`: create array with 0, 1 or nothing

`identity`, `eye`: matrix whose diagonal is equal to a value, and else is 0

## Numpy exercises

In [40]:
# Import the numpy package under the name np
import numpy as np

# Print the numpy version and the configuration
print(np.__version__)

1.21.5


### Array creation

In [42]:
# Create a numpy array of size 10, filled with zeros.
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [43]:
# Create a numpy array with values ranging from 10 to 49
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [47]:
# Create a numpy matrix of 2*2 integers, filled with ones.
np.ones((2,2),dtype=int) # remember shape is a tuple :>

array([[1, 1],
       [1, 1]])

In [48]:
# Create a numpy matrix of 3*2 float numbers, filled with ones.
np.ones((3,2), dtype=float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [49]:
# Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.
np.ones(A.shape)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [50]:
# Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.
np.zeros(A.shape)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [53]:
# there's another way to do it is using _likes function
np.zeros_like(A)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [51]:
# Create a numpy matrix of 4*4 integers, filled with fives.
np.zeros((4, 4), dtype = int) + 5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [52]:
#  Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.
np.ones(A.shape) * 7

array([[7., 7., 7.],
       [7., 7., 7.],
       [7., 7., 7.]])

In [59]:
# Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.
# identity matrix (ma tran duong cheo)
# np.eye(3) (applies to 2D array)
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [62]:
# Create a numpy array, filled with 3 random integer values between 1 and 10.
np.random.randint(10, size=3)

array([0, 9, 0])

In [64]:
# Create a 3*3*3 numpy matrix, filled with random float values.
np.random.random((3,3,3))

array([[[0.06979239, 0.11611412, 0.18493389],
        [0.2853438 , 0.96489796, 0.00664227],
        [0.08622638, 0.75131949, 0.51798252]],

       [[0.04588842, 0.90017262, 0.21327756],
        [0.23468314, 0.13098656, 0.53282621],
        [0.72635244, 0.32526988, 0.6366995 ]],

       [[0.09387003, 0.69402741, 0.24086184],
        [0.42649249, 0.67657671, 0.25680136],
        [0.49826412, 0.12773744, 0.70048135]]])

In [65]:
# Given the X python list convert it to an Y numpy array
lst = [0, 9, 6, 0]
Y = np.array(lst)
Y

array([0, 9, 6, 0])

In [67]:
# Given the X numpy array, make a copy and store it on Y.
x = np.array([1, 1, 3, 2])
y = np.copy(x)
y

array([1, 1, 3, 2])

In [68]:
# Create a numpy array with numbers from 1 to 10
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
# Create a numpy array with the odd numbers between 1 to 10
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [70]:
# Create a numpy array with numbers from 1 to 10, in descending order.
np.arange(1, 11)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [71]:
# Create a 3*3 numpy matrix, filled with values ranging from 0 to 8
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [72]:
# Show the memory size of the given Z numpy matrix
Z = np.zeros((10,10))

print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


### Array indexation

In [2]:
# Given the X numpy array, show it's first element
X = np.array(['A','B','C','D','E'])
X[0]

'A'

In [3]:
# Given the X numpy array, show it's last element
X[-1]

'E'

In [4]:
# Given the X numpy array, show it's first three elements
X[0:3]

array(['A', 'B', 'C'], dtype='<U1')

In [5]:
# Given the X numpy array, show all middle elements
X[1:-1]

array(['B', 'C', 'D'], dtype='<U1')

In [6]:
# Given the X numpy array, show the elements in reverse position
X[::-1]

array(['E', 'D', 'C', 'B', 'A'], dtype='<U1')

In [7]:
# Given the X numpy array, show the elements in an odd position
X[::2]

array(['A', 'C', 'E'], dtype='<U1')

In [8]:
# Given the X numpy matrix, show the first row elements
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
X[0]

array([1, 2, 3, 4])

In [9]:
# Given the X numpy matrix, show the last row elements
X[-1]

array([13, 14, 15, 16])

In [10]:
# Given the X numpy matrix, show the first element on first row
X[0, 0]

1

In [11]:
# Given the X numpy matrix, show the last element on last row
X[-1, -1]

16

In [12]:
# Given the X numpy matrix, show the middle row elements
X[1:-1]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
# Given the X numpy matrix, show the first two elements on the first two rows
X[0:2, 0:2]

array([[1, 2],
       [5, 6]])

In [24]:
# Given the X numpy matrix, show the last two elements on the last two rows
X[2:, 2:]

array([[11, 12],
       [15, 16]])

### Array Manipulation

In [31]:
# Convert the given integer numpy array to float
X = [-5, -3, 0, 10, 40]
X = np.array(X, float)
X

array([-5., -3.,  0., 10., 40.])

In [32]:
# Reverse the given numpy array (first element becomes last)
Y = np.array(X[::-1])
Y

array([40., 10.,  0., -3., -5.])

In [38]:
# Order (sort) the given numpy array
X = np.sort(X)
X

array([-5., -3.,  0., 10., 40.])

In [39]:
# Given the X numpy array, set the fifth element equal to 1
X[4] = 1
X

array([-5., -3.,  0., 10.,  1.])

In [41]:
# Given the X numpy array, change the 50 with a 40
X = np.array([10, 20, 30, 50])
X[3] = 40
X

array([10, 20, 30, 40])

In [44]:
# Given the X numpy matrix, change the last row with all 1
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
X[-1] = np.ones(shape =4)
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  1]])

In [45]:
# Given the X numpy matrix, change the last item on the last row with a 0
X[-1][-1] = 0
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  0]])

In [46]:
# Given the X numpy matrix, add 5 to every element
X += 5
X

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [ 6,  6,  6,  5]])

### Boolean arrays (also called masks)


In [47]:
# Given the X numpy array, make a mask showing negative elements
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])
mask = X <= 0
mask 

array([ True, False,  True,  True, False, False,  True,  True,  True,
       False])

In [48]:
# Given the X numpy array, get the negative elements
X[X < 0]

array([-1, -4, -9])

In [49]:
# Given the X numpy array, get numbers higher than 5
X[X > 5]

array([ 6, 10])

In [51]:
np.mean(X)

0.9

In [50]:
# Given the X numpy array, get numbers higher than the elements mean
X[X > np.mean(X)]

array([ 2,  5,  6, 10])

In [56]:
# Given the X numpy array, get numbers equal to 2 or 10
mask = (X == 2) | (X == 10)
X[mask]

array([ 2, 10])